// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using Universal.Entities;

namespace Universal.Mvc.Data.Migrations.DemoDB
{
    [DbContext(typeof(EFDbContext))]
    [Migration("20180510084056_InitialEFDbContext")]
    partial class InitialEFDbContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Universal.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Action");

                    b.Property<string>("Controller");

                    b.Property<string>("CssClass");

                    b.Property<string>("FatherID");

                    b.Property<string>("FatherResource");

                    b.Property<bool>("IsDisabled");

                    b.Property<bool>("IsMenu");

                    b.Property<string>("Name");

                    b.Property<string>("ResouceID");

                    b.Property<string>("RouteName");

                    b.Property<int>("Sort");

                    b.Property<string>("SysResource");

                    b.HasKey("Id");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("Universal.Entities.SysLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CreationTime");

                    b.Property<string>("FullMessage");

                    b.Property<string>("IpAddress");

                    b.Property<int?>("Level");

                    b.Property<string>("PageUrl");

                    b.Property<string>("ReferrerUrl");

                    b.Property<string>("ShortMessage");

                    b.HasKey("Id");

                    b.ToTable("SysLog");
                });

            modelBuilder.Entity("Universal.Entities.SysPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CategoryId");

                    b.Property<DateTime>("CreationTime");

                    b.Property<Guid>("Creator");

                    b.Property<Guid>("RoleId");

                    b.Property<Guid?>("SysUserId");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("RoleId");

                    b.HasIndex("SysUserId");

                    b.ToTable("SysPermission");
                });

            modelBuilder.Entity("Universal.Entities.SysRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationTime");

                    b.Property<Guid>("Creator");

                    b.Property<DateTime?>("ModifiedTime");

                    b.Property<Guid?>("Modifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.HasKey("Id");

                    b.ToTable("SysRole");
                });

            modelBuilder.Entity("Universal.Entities.SysUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Account")
                        .IsRequired();

                    b.Property<DateTime?>("AllowLoginTime");

                    b.Property<byte[]>("Avatar");

                    b.Property<DateTime>("CreationTime");

                    b.Property<Guid?>("Creator");

                    b.Property<DateTime?>("DeletedTime");

                    b.Property<string>("Email");

                    b.Property<bool>("Enabled");

                    b.Property<bool>("IsAdmin");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("LastActivityTime");

                    b.Property<string>("LastIpAddress")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("LastLoginTime");

                    b.Property<int>("LoginFailedNum");

                    b.Property<bool>("LoginLock");

                    b.Property<string>("MobilePhone");

                    b.Property<DateTime?>("ModifiedTime");

                    b.Property<Guid?>("Modifier");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Password");

                    b.Property<string>("Salt");

                    b.Property<string>("Sex")
                        .HasMaxLength(2);

                    b.HasKey("Id");

                    b.ToTable("SysUser");
                });

            modelBuilder.Entity("Universal.Entities.SysUserLoginLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("IpAddress");

                    b.Property<DateTime>("LoginTime");

                    b.Property<string>("Message");

                    b.Property<Guid?>("SysUserId");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("SysUserId");

                    b.ToTable("SysUserLoginLog");
                });

            modelBuilder.Entity("Universal.Entities.SysUserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("RoleId");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("SysUserRole");
                });

            modelBuilder.Entity("Universal.Entities.SysUserToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("ExpireTime");

                    b.Property<Guid>("SysUserId");

                    b.HasKey("Id");

                    b.HasIndex("SysUserId");

                    b.ToTable("SysUserToken");
                });

            modelBuilder.Entity("Universal.Entities.SysPermission", b =>
                {
                    b.HasOne("Universal.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Universal.Entities.SysRole", "SysRole")
                        .WithMany("SysPermission")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Universal.Entities.SysUser", "SysUser")
                        .WithMany()
                        .HasForeignKey("SysUserId");
                });

            modelBuilder.Entity("Universal.Entities.SysUserLoginLog", b =>
                {
                    b.HasOne("Universal.Entities.SysUser", "SysUser")
                        .WithMany("SysUserLoginLogs")
                        .HasForeignKey("SysUserId");
                });

            modelBuilder.Entity("Universal.Entities.SysUserRole", b =>
                {
                    b.HasOne("Universal.Entities.SysRole", "SysRole")
                        .WithMany("SysUserRole")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Universal.Entities.SysUser", "SysUser")
                        .WithMany("SysUserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Universal.Entities.SysUserToken", b =>
                {
                    b.HasOne("Universal.Entities.SysUser", "SysUser")
                        .WithMany("SysUserTokens")
                        .HasForeignKey("SysUserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
